### ISSUE TITLE
Update font sizing and colors

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#1]
- [x] Increase body font to 14px
- [x] Update headers accordingly
- [x] Change font color to very dark gray/not quite black

**Comment by joshdarby** [comment]
> Change font color to very dark gray/not quite black

Do we have a specifc hex in mind?

**Comment by MirandaEcho** [comment]
Dark gray or black is fine - @joshdarby pick whatever you think looks good.

**Comment by joshdarby** [comment]
@MirandaEcho 

> Update headers accordingly

Can you explain this more?

**Comment by MirandaEcho** [comment]
@joshdarby - if we increase the body font size, we'll likely want to increase the header sizes as well

**Comment by joshdarby** [comment]
@MirandaEcho Gotcha. That brings me to my next question.

> Increase body font to 14px

It looks like the body size for articles is already 14px? 

Example: https://borderzine.flywheelsites.com/2019/08/social-media-reflects-community-responding-with-support-as-news-of-attack-at-el-paso-walmart-unfolds/

**Comment by joshdarby** [comment]
@MirandaEcho @kaylima This is deployed to staging.

**Comment by joshdarby** [comment]
Staging being http://borderzine.flywheelsites.com/
