### ISSUE TITLE
Homepage custom sidebar

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#2]
We need to build a custom sidebar for the homepage that begins after the featured article section (2/3 1/3 layout with featured and three secondary featured)

**Comment by joshdarby** [comment]
> (2/3 1/3 layout with featured and three secondary featured)

Is that the sidebar layout or the sidebar is the 1/3 of the homepage?

**Comment by joshdarby** [comment]
Should the sidebar just be a custom widget area?

**Comment by joshdarby** [comment]
> (2/3 1/3 layout with featured and three secondary featured)
>
> Is that the sidebar layout or the sidebar is the 1/3 of the homepage?

No, the sidebar will be below these featured article sections.

> Should the sidebar just be a custom widget area?

Yes
