### ISSUE TITLE
author images

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-borderzine#21]
We've removed a handful of plugins. Previously, Borderzine was using a plugin to add in author images. 

Right now author images aren't showing up.

1. We'd like them to be able to upload author images into the Author settings (common w/ Largo). 
2. We want the author images to show up next to author bios on posts they've authored and author detail pages.

**Comment by joshdarby** [comment]
@kaylima Do you have an example of where these aren't showing up? I was able to add an image for the user `Molly Hunter` and it appears in her byline.

Example: http://borderzine.flywheelsites.com/2019/08/social-media-reflects-community-responding-with-support-as-news-of-attack-at-el-paso-walmart-unfolds/

**Comment by joshdarby** [comment]
The author images were missing on staging because the plugin they were using on prod, [user photo](https://wordpress.org/plugins/user-photo/), was not present on the staging environment.

**Comment by kaylima** [comment]
@joshdarby if we are switching to a WP-author/user image upload, rather than the "user photo" plugin, is there a way to migrate them?

**Comment by joshdarby** [comment]
@kaylima I opened #38 which will check for a photo uploaded by the plugin to display and then fallback to the default Largo avatar image field, so they can still use the user photo plugin and we don't need to worry about migrating anything.

**Comment by kaylima** [comment]
Got it - I'm a bit behind! :) Thanks @joshdarby 👍
