### ISSUE TITLE
thumbnail missing from homepage

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-borderzine#23]
1. Go to http://borderzine.flywheelsites.com/
2. Look at "Sisterhood of the Traveling Boots that began as Beto..."

RESULT: Thumbnail image missing
EXPECT: should pull from the featured image

**Comment by joshdarby** [comment]
@kaylima This was just an oopsie on the widget settings. It had `Thumbnail Image` set to `None`. I've updated it to display one like the others.
