### ISSUE TITLE
search by author

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-borderzine#25]
EXPECT: should be able to search an author's name on the site and have it show up in results

**Comment by joshdarby** [comment]
> have it show up in results
@kaylima Is "it" in this context referring to the authors author page, or just posts that are written by the author?

**Comment by kaylima** [comment]
ah, I meant the authors name. so anywhere the name is referenced. could be a combination of the authors landing page, posts written by the author, or any posts their name shows up in. @joshdarby let me know if there's any challenges to consider for those
