### ISSUE TITLE
Updates to byline area on article pages

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#3]
Add the following to the author byline area at the top of articles:
- [x] Thumbnail image of author
- [x] Bio excerpt
- [x] "More" button that links to full author bio

byline at the top only, not at bottom

**Comment by joshdarby** [comment]
What if the author doesn't have a thumbnail image? Should there be a default image that displays or none at all?

**Comment by MirandaEcho** [comment]
Ideally none, but if that's too tricky than we'll do a default image.

**Comment by joshdarby** [comment]
- [ ] Remove bio excerpt from byline

**Comment by joshdarby** [comment]
@kaylima Do they also want the `More by xyz` button removed from the top of article byline, or just the excerpt?

**Comment by kaylima** [comment]
@joshdarby yes, please remove bio, more by xyz and the email button. thanks! (leave only the "by xyz" byline)
