### ISSUE TITLE
Our stories and our voices dropdown navigation

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#31]
Create dropdown navigations for "Our Stories" and "Our Voices" underneath the header section. 
[Our Border Life landing page.pdf](https://github.com/INN/umbrella-borderzine/files/3650043/Our.Border.Life.landing.page.pdf)

**Comment by benlk** [comment]
Where are these navigations supposed to link to, and how should they be populated?

**Comment by kaylima** [comment]
@benlk I imagined these as anchor links to the sections in this landing page. if that can be automatically populated based on widget area headers, etc. that would be awesome. if not, we can train them on how to add/update with manual anchor links. (I think.) Let me know if there's anything tricky about that which I'm forgetting/not understanding. Thanks!

**Comment by benlk** [comment]
I guess we could do something with javascript that, on page load, checks for items with class `.widgettitle`, finds the parent `.widget`, assigns the widget an ID or anchor if it doesn't don't have one, and then populates a list.

If we wanted to auto-populate via selector the list of elements on the page, by separation between "our voices" and "our stories", the separation of widget areas and custom HTML described in the doodle I posted to Slack would not work.

![plan-of-regions](https://user-images.githubusercontent.com/1754187/65725052-bd207480-e07f-11e9-8605-f3a6362ea87b.png)

The division between "our voices" and "our stories" falls in the middle of that "Custom HTML or hardcoded" section. Normally, if we'd want to have a selector for "Our voices" and "our stories", we'd want the DOM to be shaped kinda like

```
page
	(header image)
	(header text/logo)
	(container for controls)

	div#our-voices (container)
		widget featured stories
		widget photo gallery
		widget for 100 questions
	div#our-stories (container)
		thing for our voices
		widget podcasts
		widget audio
		widget radio
```
Note that the widgets are descendents of the "our voices" and "our stories" container elements

But if we want to keep this widgetizable, what we'll end up with is:
```
page
	(header image)
	(header text/logo)
	(container for controls)

	our stories heading
	widget featured stories
	widget photo gallery
	widget for 100 questions
	our voices heading
	thing for our voices
	widget podcasts
	widget audio
	widget radio
```
Sure, we could wrap the whole homepage bottom in a container, but that doesn't separate the "our stories" and "our voices" headings

Could we consolidate into one drop-down for something like "our coverage"?


But why should there be a dropdown if people will scroll on the page? This page is nowhere near long enough that there'd be a need to include a Snowfall-style table of contents.

**Comment by MirandaEcho** [comment]
Closing to take a different approach.
