### ISSUE TITLE
"Our stories sidebar"

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#37]
- [ ] Miranda will get title from Kate and find out if it needs to be editable.
[Our Border Life landing page.pdf](https://github.com/INN/umbrella-borderzine/files/3650059/Our.Border.Life.landing.page.pdf)

**Comment by benlk** [comment]
This is the "100 questions Ebook" item from the mockup, correct?

<img width="840" alt="Screen Shot 2019-09-25 at 14 28 18 " src="https://user-images.githubusercontent.com/1754187/65629079-bcfd7780-dfa0-11e9-9e9c-a9f793d0309f.png">

**Comment by MirandaEcho** [comment]
Closing this, since its no longer relevant in the revised wireframe.
