### ISSUE TITLE
Custom pop out sidebar for article pages

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#4]
Create a sidebar that pops out after a certain scroll distance with calls to action on article pages. 

Move current sidebar content to the bottom of article pages.

**Comment by joshdarby** [comment]
Should this "pop out" to the left? Right? 

Where should it pop out from? 

How fast should it pop out?

**Comment by MirandaEcho** [comment]
We will use the pop up plugin for this - it will pop out from the right side of the screen.

**Comment by MirandaEcho** [comment]
We would like to use the related content widget - would this work with the pop up maker plugin?

Ideally it will display a list of related content from series.

**Comment by joshdarby** [comment]
> We will use the pop up plugin for this

@benlk Do we have a default go-to pop up plugin we use?

**Comment by benlk** [comment]
We've used https://wordpress.org/plugins/popup-maker/ with good results in the past.

**Comment by joshdarby** [comment]
I think we'll need to create a shortcode to render the related content widget if we're going with a plugin since the pop-up is actually just a custom post type, not a widget area.

@benlk Any other workarounds you can think of?

**Comment by benlk** [comment]
Rather than using a shortcode to render the widget, we could use a shortcode to render the widget area that contains the widget. That would allow them to change the widgets used in the popup. 

https://github.com/INN/super-cool-ad-inserter-plugin/blob/master/inc/scaip-shortcode.php#L29-L51
