### ISSUE TITLE
Move content from sidebar of articles pages to bottom

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#5]
Move all the things from the sidebar into the bottom of the page so we can go full-width with article pages.

**Comment by joshdarby** [comment]
@MirandaEcho @kaylima I've updated the settings on the staging site so that the one column layout is now the default post layout. Do we still want to move everything that is in the main sidebar widget area to the Article Bottom widget area as well, or only specific widgets?

**Comment by kaylima** [comment]
@joshdarby can you provide a list of what those widgets are, please? thanks!

**Comment by joshdarby** [comment]
@kaylima Before I changed it over to the one column layout, the post pages were pulling in the same sidebar that is on the [homepage](https://borderzine.flywheelsites.com/).

The widgets in it are:
- Life on the Borderline (text)
- Multimedia skills for the 21st Century (text)
- Special Projects (text)
- Join our email newsletter list (text)
- Sponsors (text)
-  Like us on Facebook (text)
- Sponsor spotlight (text)
