### ISSUE TITLE
Update donation page to match current site

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-borderzine#51]
1. Go to staging site: http://borderzine.flywheelsites.com/donate/
2. Compare with live site: http://borderzine.com/donate/

RESULT: styling does not match. check w/ @MirandaEcho on budget and then clean up any low-hanging fruit (styles)

**Comment by benlk** [comment]
What were the specific areas where styles don't match? There's some font-size stuff that we can look into, but I have a sneaking suspicion that that's inline styles.

**Comment by benlk** [comment]
It was abuse of heading elements. I've cleaned that up, but encountered https://github.com/INN/umbrella-borderzine/issues/74
