### ISSUE TITLE
Mobile: Remove excerpt and change to thumbnail on the right for photos

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#66]
Photo sizes on mobile
- Remove excerpt
- Thumbnail on the right

**Comment by joshdarby** [comment]
@MirandaEcho @kaylima Is this for stories on the homepage? If so, is this for _every_ story on the homepage?

**Comment by kaylima** [comment]
@joshdarby 
- remove excerpts from all 
- make a thumbnail for all the secondary items in mobile (i.e not the primary featured – that will still be a larger image on mobile)

Can look like the diversity section on mobile (so, in a way, related to #65)

Should look like this on mobile:
![Screen Shot 2019-10-02 at 3 53 15 PM](https://user-images.githubusercontent.com/15877728/66084925-0ca5eb00-e52d-11e9-85f2-6648da6d31a6.png)

**Comment by kaylima** [comment]
NOTE: Should look like above _EXCEPT_ they want thumbnails on the right. Thanks! @joshdarby

**Comment by benlk** [comment]
To be clear, are we removing the excerpts outright, or just hiding the excerpts on mobile?

**Comment by MirandaEcho** [comment]
@benlk  just on mobile
