### ISSUE TITLE
Posts showing up in multiple categories

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#68]
Example: http://borderzine.flywheelsites.com/2019/05/12-professors-heading-to-u-s-mexico-border-for-dow-jones-news-fund-multimedia-training-academy-2019/

Is showing up under Diversity and Ideas on the homepage as well as Media, but it only has the "media" category assigned.

**Comment by joshdarby** [comment]
@MirandaEcho This is probably because `Media` is a child category of `Diversity and Ideas`.

**Comment by joshdarby** [comment]
Checking `Avoid Duplicate Posts?` fixes the issue of the posts displaying twice.
